In [ ]:
import pandas as pd
from pathlib import Path

# 1. Automatically get project root directory and create target folder
project_dir = Path.cwd()
output_folder = project_dir / "data" / "clean"
output_folder.mkdir(parents=True, exist_ok=True)

# 2. Define path to Excel file
excel_file = project_dir / "E_commerce_cleaned.xlsx"

# 3. Validation columns to remove before exporting
columns_to_drop = {
    "CLEAN_orders": ["customer_check"],
    "CLEAN_order_items": ["order_check", "product_check"],
    "CLEAN_returns": ["order_check"],
}

# 4. Read sheets and export CLEAN_ tables to CSV
xls = pd.ExcelFile(excel_file)

for sheet_name in xls.sheet_names:
    if sheet_name.startswith("CLEAN_"):
        df = pd.read_excel(xls, sheet_name=sheet_name)

        # Remove temporary validation columns
        if sheet_name in columns_to_drop:
            df = df.drop(columns=columns_to_drop[sheet_name], errors="ignore")

        # Save to CSV
        csv_path = output_folder / f"{sheet_name}.csv"
        df.to_csv(csv_path, index=False)

        print(f"Saved: {csv_path}")

print("\nAll clean tables exported successfully!")

Saved: c:\Users\Asus\Desktop\e_commerce_dataset_analysis\ecommerce_clean_csvs\CLEAN_customers.csv
Saved: c:\Users\Asus\Desktop\e_commerce_dataset_analysis\ecommerce_clean_csvs\CLEAN_products.csv
Saved: c:\Users\Asus\Desktop\e_commerce_dataset_analysis\ecommerce_clean_csvs\CLEAN_orders.csv
Saved: c:\Users\Asus\Desktop\e_commerce_dataset_analysis\ecommerce_clean_csvs\CLEAN_order_items.csv
Saved: c:\Users\Asus\Desktop\e_commerce_dataset_analysis\ecommerce_clean_csvs\CLEAN_returns.csv

All clean tables exported successfully!

## Customers

In [ ]:
df_customers = pd.read_csv("data/clean/CLEAN_customers.csv")
df_customers.isna().sum()

customer_id      0
first_name       0
last_name        0
email          120
city             0
signup_date      0
age             80
full_name        0
dtype: int64

## Orders

In [ ]:
df_orders = pd.read_csv("data/clean/CLEAN_orders.csv")
df_orders = df_orders.dropna()
df_orders.isna().sum()

order_id          0
customer_id       0
order_date        0
payment_method    0
sales_channel     0
order_status      0
shipping_city     0
shipping_fee      0
dtype: int64

In [4]:
df_orders_filter = df_orders[df_orders['customer_id'] == 'UNKNOWN']
df_orders_filter.info()

<class 'pandas.DataFrame'>
Index: 80 entries, 511 to 21798
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        80 non-null     str
 1   customer_id     80 non-null     str
 2   order_date      80 non-null     str
 3   payment_method  80 non-null     str
 4   sales_channel   80 non-null     str
 5   order_status    80 non-null     str
 6   shipping_city   80 non-null     str
 7   shipping_fee    80 non-null     float64
dtypes: float64(1), str(7)
memory usage: 5.6 KB

## Filter out 'UNKNOWN' customer IDs

In [5]:
df_orders_clean = df_orders[df_orders['customer_id'] != 'UNKNOWN'].copy()
# Save directly over the clean CSV
# df_orders_clean.to_csv("ecommerce_clean_csvs/CLEAN_orders.csv", index=False)

In [6]:
# Convert to string to safely run string methods
order_ids = df_orders["order_id"].astype(str)

# Find rows with leading/trailing spaces or internal spaces
has_spaces = order_ids.str.contains(r"\s", regex=True)

# Filter the DataFrame to display those rows
spaced_rows = df_orders[has_spaces]

print(f"Total rows with spaces in 'order_id': {len(spaced_rows)}")
spaced_rows.head()

Total rows with spaces in 'order_id': 0

Empty DataFrame
Columns: [order_id, customer_id, order_date, payment_method, sales_channel, order_status, shipping_city, shipping_fee]
Index: []

## Returns

In [ ]:
df_returns = pd.read_csv("data/clean/CLEAN_returns.csv")
df_returns.isna().sum()

return_id        0
order_id         0
return_date      0
return_reason    0
refund_amount    0
dtype: int64

In [8]:
df_returns_filter = df_returns[df_returns['return_id'] == 'UNKNOWN']
df_returns_filter.info()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      0 non-null      str
 1   order_id       0 non-null      str
 2   return_date    0 non-null      str
 3   return_reason  0 non-null      str
 4   refund_amount  0 non-null      float64
dtypes: float64(1), str(4)
memory usage: 132.0 bytes

In [9]:
df_returns[df_returns['order_id'] == 'UNKNOWN']

Empty DataFrame
Columns: [return_id, order_id, return_date, return_reason, refund_amount]
Index: []

## Products

In [ ]:
df_products = pd.read_csv("data/clean/CLEAN_products.csv")
df_products.isna().sum()

product_id       0
product_name     0
category         0
brand            0
unit_cost       10
list_price      15
dtype: int64

## Order Items

In [ ]:
df_order_items = pd.read_csv("data/clean/CLEAN_order_items.csv")
df_order_items.isna().sum()

order_item_id    0
order_id         0
product_id       0
quantity         0
unit_price       0
discount_pct     0
dtype: int64

In [12]:
df_order_items[df_order_items['order_id'] == 'UNKNOWN']

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price, discount_pct]
Index: []

In [13]:
df_order_items[df_order_items['product_id'] == 'UNKNOWN']

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price, discount_pct]
Index: []

In [ ]:
# Clean whitespace to avoid subtle string mismatches
df_customers["customer_id"] = df_customers["customer_id"].astype(str).str.strip()
df_products["product_id"] = df_products["product_id"].astype(str).str.strip()
df_orders["order_id"] = df_orders["order_id"].astype(str).str.strip()
df_orders["customer_id"] = df_orders["customer_id"].astype(str).str.strip()
df_order_items["order_id"] = df_order_items["order_id"].astype(str).str.strip()
df_order_items["product_id"] = df_order_items["product_id"].astype(str).str.strip()
df_returns["order_id"] = df_returns["order_id"].astype(str).str.strip()

# Create lookup sets of valid parent IDs
valid_cust_ids = set(df_customers["customer_id"])
valid_prod_ids = set(df_products["product_id"])

# 1. Filter orders against customers
df_orders_clean = df_orders[
    df_orders["customer_id"].isin(valid_cust_ids)
].copy()
valid_order_ids = set(df_orders_clean["order_id"])

# 2. Filter order_items against BOTH valid orders AND valid products
df_items_clean = df_order_items[
    df_order_items["order_id"].isin(valid_order_ids)
    & df_order_items["product_id"].isin(valid_prod_ids)
].copy()

# 3. Filter returns against valid orders
df_returns_clean = df_returns[
    df_returns["order_id"].isin(valid_order_ids)
].copy()

# Overwrite CSVs
df_orders_clean.to_csv("data/clean/CLEAN_orders.csv", index=False)
df_items_clean.to_csv("data/clean/CLEAN_order_items.csv", index=False)
df_returns_clean.to_csv("data/clean/CLEAN_returns.csv", index=False)

print(f"Dropped {len(df_order_items) - len(df_items_clean)} orphan order items.")
print(f"Dropped {len(df_returns) - len(df_returns_clean)} orphan returns.")

Dropped 413 orphan order items.
Dropped 34 orphan returns.